apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cc024hm03-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cc024hm03-java-quarkus-gitops